In [1]:
from datamanipulator import DataManipulator

In [12]:
import torch
import numpy as np
a = torch.Tensor(torch.from_numpy(np.full(4,2)))
a

tensor([2, 2, 2, 2])

In [42]:
def resenbrock(x0,x1):
    # y = 100*(x1.data - x0.data **2)**2 + (x0.data-1)**2
    y = 100*(x1 - x0 **2)**2 + (x0-1)**2
    # y = torch.Tensor([y])
    print(y)
    return y

In [43]:
x0 = torch.tensor(0.0,requires_grad=True)
x1 = torch.tensor(2.0,requires_grad=True)

lr = 0.001
iterse = 10000

for i in range(iterse):
    if i % 100 == 0:
        print(x0.item(), x1.item())
    
    y = resenbrock(x0,x1)
    y.backward()

    x0.data -= lr*x0.grad.data
    x1.data -= lr*x1.grad.data

    x0.grad.zero_()
    x1.grad.zero_()
print(x0.item(), x1.item())

0.0 2.0
tensor(401., grad_fn=<AddBackward0>)
tensor(256.9947, grad_fn=<AddBackward0>)
tensor(164.8225, grad_fn=<AddBackward0>)
tensor(105.8187, grad_fn=<AddBackward0>)
tensor(68.0390, grad_fn=<AddBackward0>)
tensor(43.8422, grad_fn=<AddBackward0>)
tensor(28.3409, grad_fn=<AddBackward0>)
tensor(18.4091, grad_fn=<AddBackward0>)
tensor(12.0469, grad_fn=<AddBackward0>)
tensor(7.9734, grad_fn=<AddBackward0>)
tensor(5.3675, grad_fn=<AddBackward0>)
tensor(3.7025, grad_fn=<AddBackward0>)
tensor(2.6401, grad_fn=<AddBackward0>)
tensor(1.9630, grad_fn=<AddBackward0>)
tensor(1.5319, grad_fn=<AddBackward0>)
tensor(1.2577, grad_fn=<AddBackward0>)
tensor(1.0831, grad_fn=<AddBackward0>)
tensor(0.9717, grad_fn=<AddBackward0>)
tensor(0.9005, grad_fn=<AddBackward0>)
tensor(0.8545, grad_fn=<AddBackward0>)
tensor(0.8245, grad_fn=<AddBackward0>)
tensor(0.8046, grad_fn=<AddBackward0>)
tensor(0.7910, grad_fn=<AddBackward0>)
tensor(0.7814, grad_fn=<AddBackward0>)
tensor(0.7743, grad_fn=<AddBackward0>)
tensor(0

In [52]:
a = torch.Tensor(2.0,requires_grad=True)
print(a)
b = torch.tensor(2)
a+b


TypeError: new() received an invalid combination of arguments - got (float, requires_grad=bool), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [2]:
data_manipulator = DataManipulator(1,[0])
data_manipulator.set_dataset()


In [3]:
data_manipulator.set_dataloader(30)
train_loader = data_manipulator.dataloader

In [5]:
from torch.nn import functional as F
import torch
import numpy as np
for data, label in train_loader:
    break
print(data.shape)
print(label.shape)
# data_b = data.view(data.size(0),-1)
# print(data_b.shape)
# label_a = label.view(-1).astype(int)

# # label_b = torch.Tensor(np.eye(6)[label_a])
# print(label_a)

# one_test = np.eye(6)[label_a]
label = label.to(torch.int64)

print(label.dtype)
one_hot = F.one_hot(label, num_classes=6)

print(one_hot)


torch.Size([30, 45, 4])
torch.Size([30])
torch.int64
tensor([[0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0]])


In [5]:
a = torch.Tensor([0,1,2,3,4,5])
print(a)


tensor([0., 1., 2., 3., 4., 5.])


In [17]:
F.one_hot(label_b, num_classes=6)

RuntimeError: one_hot is only applicable to index tensor.

In [11]:
dataset.d

NameError: name 'dataset' is not defined